services:
  web:
    build: docker
    ports:
      - 8443:8443
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/clubtenis
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  db:
    image: mysql:9.2
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=clubtenis
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 5
    restart: on-failure

volumes:
  db_data: